"use client";

import { useEffect, useState } from "react";

type Settings = { enabled: boolean; maxRecoveryAttempts: number; quietHoursStart: number; quietHoursEnd: number; approvalThresholdPaise: number; defaultRecoveryDelayMin: number; demoMode: boolean; aiMessageGeneration: boolean; simulatedCommunication: boolean; source: "database" | "environment" };

const stages = ["Observe", "Diagnose", "Prioritize", "Policy Check", "Act", "Verify", "Learn / Stop"];

export function AgentControl() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [stage, setStage] = useState(0);
  const [running, setRunning] = useState(true);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [feedback, setFeedback] = useState("");
  useEffect(() => { fetch("/api/agent-settings").then(async (response) => { const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error?.message ?? "Unable to load settings."); setSettings(body.data); }).catch((reason: unknown) => setFeedback(reason instanceof Error ? reason.message : "Unable to load settings.")).finally(() => setLoading(false)); }, []);

  function update<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings((current) => current ? { ...current, [key]: value } : current); }
  async function save() {
    if (!settings || settings.source === "environment") return;
    setSaving(true); setFeedback("");
    const payload = { enabled: settings.enabled, maxRecoveryAttempts: settings.maxRecoveryAttempts, quietHoursStart: settings.quietHoursStart, quietHoursEnd: settings.quietHoursEnd, approvalThresholdPaise: settings.approvalThresholdPaise, defaultRecoveryDelayMin: settings.defaultRecoveryDelayMin, demoMode: settings.demoMode, aiMessageGeneration: settings.aiMessageGeneration, simulatedCommunication: settings.simulatedCommunication };
    try { const response = await fetch("/api/agent-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error?.message ?? "Settings could not be saved."); setSettings(body.data); setFeedback("Agent settings saved."); } catch (reason) { setFeedback(reason instanceof Error ? reason.message : "Settings could not be saved."); } finally { setSaving(false); }
  }
  if (loading) return <section className="panel state" role="status">Loading agent settings...</section>;
  if (!settings) return <section className="panel state error" role="alert"><strong>Agent settings unavailable</strong><p>{feedback}</p><button type="button" onClick={() => window.location.reload()}>Retry</button></section>;
  return <>
    <section className="panel agent-stage"><div className="title"><div><h2>Manual recovery agent</h2><p>{running ? "Ready for controlled manual execution" : "Paused by merchant"}</p></div><span className={`status ${running ? "available" : "unavailable"}`}>{running ? "RUNNING" : "PAUSED"}</span></div><div className="stage-row">{stages.map((item, index) => <button type="button" className={index === stage ? "stage active" : "stage"} onClick={() => setStage(index)} key={item}><b>{index + 1}</b><span>{item}</span></button>)}</div><div className="case-actions"><button type="button" onClick={() => { setRunning(true); setStage(0); setFeedback("Agent run started in manual mode."); }}>Run Agent</button><button type="button" className="outline" onClick={() => { setRunning(false); setFeedback("Agent paused."); }}>Pause Agent</button><button type="button" className="outline" onClick={() => { setStage((value) => Math.min(value + 1, stages.length - 1)); setFeedback("Advanced one controlled stage."); }}>Process Next Case</button><button type="button" className="danger-button" onClick={() => { setRunning(false); setStage(stages.length - 1); setFeedback("Demo session reset."); }}>Reset Demo</button></div></section>
    <section className="panel settings-form"><div className="title"><div><h2>Policy settings</h2><p>Safety controls apply before any recovery action.</p></div><span className={`status ${settings.source === "database" ? "available" : "simulated"}`}>{settings.source === "database" ? "Saved" : "Environment defaults"}</span></div><div className="form-grid"><label className="toggle"><input type="checkbox" checked={settings.enabled} onChange={(event) => update("enabled", event.target.checked)} /> Agent enabled</label><label className="toggle"><input type="checkbox" checked={settings.demoMode} onChange={(event) => update("demoMode", event.target.checked)} /> Demo mode</label><label className="toggle"><input type="checkbox" checked={settings.aiMessageGeneration} onChange={(event) => update("aiMessageGeneration", event.target.checked)} /> AI message generation</label><label className="toggle"><input type="checkbox" checked={settings.simulatedCommunication} onChange={(event) => update("simulatedCommunication", event.target.checked)} /> Simulated communication</label><label>Maximum recovery attempts<input type="number" min="1" max="10" value={settings.maxRecoveryAttempts} onChange={(event) => update("maxRecoveryAttempts", Number(event.target.value))} /></label><label>Quiet-hour start<input type="number" min="0" max="23" value={settings.quietHoursStart} onChange={(event) => update("quietHoursStart", Number(event.target.value))} /></label><label>Quiet-hour end<input type="number" min="0" max="23" value={settings.quietHoursEnd} onChange={(event) => update("quietHoursEnd", Number(event.target.value))} /></label><label>Approval threshold (paise)<input type="number" min="0" value={settings.approvalThresholdPaise} onChange={(event) => update("approvalThresholdPaise", Number(event.target.value))} /></label><label>Default recovery delay (minutes)<input type="number" min="0" value={settings.defaultRecoveryDelayMin} onChange={(event) => update("defaultRecoveryDelayMin", Number(event.target.value))} /></label></div><button type="button" disabled={saving || settings.source === "environment"} onClick={save}>{saving ? "Saving..." : "Save settings"}</button>{settings.source === "environment" && <p className="form-hint">Connect Neon PostgreSQL to persist changes. Environment defaults remain active in demo mode.</p>}{feedback && <p className={feedback.includes("could not") || feedback.includes("unavailable") ? "error" : "success"} role="status">{feedback}</p>}</section>
  </>;
}
